spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://goorm.cv8yu8ywovhc.ap-northeast-2.rds.amazonaws.com:3306/goorm?serverTimezone=Asia/Seoul
  username: admin
  password: dbtjddus12^
